# Generated by Django 5.2.8 on 2026-01-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_app', '0003_medicalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='prediction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
