# Generated by Django 5.2.10 on 2026-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_app', '0004_alter_medicalreport_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
