# Generated by Django 5.2.10 on 2026-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_app', '0005_medicalreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
