# Generated by Django 5.2.10 on 2026-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_app', '0006_alter_medicalreport_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='risk_factor',
            field=models.FloatField(default=0.0),
        ),
    ]
