# Generated by Django 5.2.9 on 2026-04-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_app', '0007_medicalreport_risk_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
