from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import io
import os
from django.conf import settings

def generate_pdf_report(report_data):
    """
    Generate a PDF report for the patient.
    report_data: dict containing 'patient_name', 'patient_id', 'prediction', 'doctor_name', 'image_path'
    """
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # --- Header ---
    p.setFont("Helvetica-Bold", 24)
    p.setFillColorRGB(0.06, 0.46, 0.43) # Teal color
    p.drawString(50, height - 60, "Eye4Heart AI — Diagnostic Report")
    
    p.setLineWidth(1)
    p.setStrokeColorRGB(0.8, 0.8, 0.8)
    p.line(50, height - 80, width - 50, height - 80)

    # --- Patient Info ---
    p.setFont("Helvetica", 12)
    p.setFillColorRGB(0.2, 0.2, 0.2)
    y_start = height - 130
    
    p.drawString(50, y_start, f"Patient Name: {report_data.get('patient_name', 'N/A')}")
    p.drawString(50, y_start - 20, f"Patient ID: {report_data.get('patient_id', 'N/A')}")
    p.drawString(50, y_start - 40, f"Consulting Doctor: {report_data.get('doctor_name', 'N/A')}")
    p.drawString(50, y_start - 60, f"Date: {report_data.get('date', 'N/A')}")

    p.setFont("Helvetica-Bold", 14)
    p.drawString(50, y_start - 100, "AI Analysis Status:")
    
    prediction = report_data.get('prediction', 'Unknown')
    risk = report_data.get('risk_factor', 'N/A')
    
    # Textual Risk Label Standard
    pred_clean = str(prediction or "").lower()
    if 'high' in pred_clean:
        display_risk = "High Risk"
        p.setFillColorRGB(0.8, 0, 0) # Red
    elif 'low' in pred_clean:
        display_risk = "Low Risk"
        p.setFillColorRGB(0, 0.5, 0) # Green
    else:
        display_risk = prediction
        p.setFillColorRGB(0, 0, 0)
        
    p.setFont("Helvetica-Bold", 18)
    p.drawString(200, y_start - 100, str(display_risk).upper())

    # --- Risk Factor Section ---
    p.setFillColorRGB(0.1, 0.1, 0.1)
    p.setFont("Helvetica-Bold", 14)
    p.drawString(50, y_start - 140, "Calculated CVD Risk Factor:")
    
    # Risk Meter Bar
    p.setStrokeColorRGB(0.9, 0.9, 0.9)
    p.setFillColorRGB(0.95, 0.95, 0.95)
    p.roundRect(250, y_start - 142, 200, 15, 3, fill=1)
    
    try:
        risk_val = int(risk.replace('%', '')) if isinstance(risk, str) else int(risk)
        fill_color = (0, 0.5, 0) if risk_val < 30 else (0.8, 0.6, 0) if risk_val < 70 else (0.8, 0, 0)
        p.setFillColorRGB(*fill_color)
        p.roundRect(250, y_start - 142, (risk_val/100.0)*200, 15, 3, fill=1)
        p.setFont("Helvetica-Bold", 16)
        p.drawString(460, y_start - 140, f"{risk_val}%")
    except:
        p.drawString(250, y_start - 140, "N/A")

    # --- Future clinical notes or additional metrics could go here ---

    # --- Footer ---
    p.setFont("Helvetica", 10)
    p.setFillColorRGB(0.6, 0.6, 0.6)
    p.drawString(50, 50, "Generated by Eye4Heart AI System. This is an automated preliminary report.")
    p.drawString(width - 150, 50, "Page 1 of 1")

    p.showPage()
    p.save()
    
    buffer.seek(0)
    return buffer
